# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "app for learning"
client_id = "e0f37b0435832fadf7a31dc75051f066"
application_url = "https://3e76-2a0d-6fc7-441-5a82-909a-6cc7-a22-283e.ngrok-free.app"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://3e76-2a0d-6fc7-441-5a82-909a-6cc7-a22-283e.ngrok-free.app/auth/callback",
  "https://3e76-2a0d-6fc7-441-5a82-909a-6cc7-a22-283e.ngrok-free.app/auth/shopify/callback",
  "https://3e76-2a0d-6fc7-441-5a82-909a-6cc7-a22-283e.ngrok-free.app/api/auth/callback",
  "https://3e76-2a0d-6fc7-441-5a82-909a-6cc7-a22-283e.ngrok-free.app/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "quickstart-8a9ac96d.myshopify.com"
